<?php

$configuration = array(
    CONFIGURATION_DATABASE => array(
        CONFIGURATION_DATABASE_SERVER => "localhost",
        CONFIGURATION_DATABASE_NAME => "release",
        CONFIGURATION_DATABASE_TYPE => "1",
        CONFIGURATION_DATABASE_USER => "root",
        CONFIGURATION_DATABASE_PASSWORD => "admin",
        CONFIGURATION_DATABASE_SURVEY => "main"
    ),
    CONFIGURATION_GENERAL => array(
        CONFIGURATION_GENERAL_STARTUP => "1",
        CONFIGURATION_GENERAL_DEVICE => "1"
    ),
    CONFIGURATION_SAMPLE => array(
        CONFIGURATION_SAMPLE_PANEL => "1",
        CONFIGURATION_SAMPLE_TRACKING => "2",
        CONFIGURATION_SAMPLE_INTERVIEWADDRESS => "2",
        CONFIGURATION_SAMPLE_PROXYCODE => "2",
        CONFIGURATION_SAMPLE_PROXYCONTACT => "2",
        CONFIGURATION_SAMPLE_COMMUNICATION => "",
        CONFIGURATION_SAMPLE_FILELOCATION => ""
    ),
    CONFIGURATION_ENCRYPTION => array(
        CONFIGURATION_ENCRYPTION_DATA => "rj5559!&sp!#43n06y4xhr#y*z&*hw*b",
        CONFIGURATION_ENCRYPTION_LOGINCODES => "rj5559!&sp!#43n06y4xhr#y*z&*hw*b",
        CONFIGURATION_ENCRYPTION_ADMIN => "rj5559!&sp!#43n06y4xhr#y*z&*hw*b",
        CONFIGURATION_ENCRYPTION_PERSONAL => "rj5559!&sp!#43n06y4xhr#y*z&*hw*b",
        CONFIGURATION_ENCRYPTION_REMARK => "rj5559!&sp!#43n06y4xhr#y*z&*hw*b",
        CONFIGURATION_ENCRYPTION_CONTACTREMARK => "rj5559!&sp!#43n06y4xhr#y*z&*hw*b",
        CONFIGURATION_ENCRYPTION_CONTACTNAME => "rj5559!&sp!#43n06y4xhr#y*z&*hw*b",
        CONFIGURATION_ENCRYPTION_ACTION_PARAMS => "rj5559!&sp!#43n06y4xhr#y*z&*hw*b",
        CONFIGURATION_ENCRYPTION_DIRECT => "rj5559!&sp!#43n06y4xhr#y*z&*hw*b#1sa",
        CONFIGURATION_ENCRYPTION_LAB => "rj5559!&sp!#43n06y4xhr#y*z&*hw*b",
        CONFIGURATION_ENCRYPTION_FILE => "rj5559!&sp!#43n06y4xhr#y*z&*hw*b3"
    ),
    CONFIGURATION_DATETIME => array(
        CONFIGURATION_DATETIME_TIMEZONE => "America/Los_Angeles",
        CONFIGURATION_DATETIME_USFORMAT_SMS => "true",
        CONFIGURATION_DATETIME_USFORMAT_SURVEY => "true",
        CONFIGURATION_DATETIME_MINUTES_SMS => "true",
        CONFIGURATION_DATETIME_MINUTES_SURVEY => "true",
        CONFIGURATION_DATETIME_SECONDS_SMS => "true",
        CONFIGURATION_DATETIME_SECONDS_SURVEY => "true"
    ),
    CONFIGURATION_LOGGING => array(
        CONFIGURATION_LOGGING_TIMINGS => "1",
        CONFIGURATION_LOGGING_PARAMS => "1",
        CONFIGURATION_LOGGING_ACTIONS => "1",
        CONFIGURATION_LOGGING_PARADATA => "1",
        CONFIGURATION_LOGGING_TABSWITCH => "1",
        CONFIGURATION_LOGGING_MOUSE => "10000"
    ),
    CONFIGURATION_SESSION => array(
        CONFIGURATION_SESSION_WARN => "2",
        CONFIGURATION_SESSION_TIMEOUT => "1800",
        CONFIGURATION_SESSION_LOGOUT => "",
        CONFIGURATION_SESSION_REDIRECT => "",
        CONFIGURATION_SESSION_PING => "5000"
    ),
    CONFIGURATION_PERFORMANCE => array(
        CONFIGURATION_PERFORMANCE_DATA_FROM_STATE => "2",
        CONFIGURATION_PERFORMANCE_PREPARE_QUERIES => "2",
        CONFIGURATION_PERFORMANCE_UNSERIALIZE => "2",
        CONFIGURATION_PERFORMANCE_USE_DATARECORDS => "2",
        CONFIGURATION_PERFORMANCE_USE_DYNAMIC_MINIFY => "1",
        CONFIGURATION_PERFORMANCE_USE_LOCKING => "2",
        CONFIGURATION_PERFORMANCE_USE_TRANSACTIONS => "1"
    )
);
?>